<script setup></script>

<template>
 <div class="loadingio-spinner-spinner-c1lc0tehm7v">
  <div class="ldio-37t7hale7vr">
    <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
  </div>
</div>
</template>


<style scoped>
@keyframes ldio-37t7hale7vr {
  0% { opacity: 1 }
  100% { opacity: 0 }
}
.ldio-37t7hale7vr div {
  left: 147.58px;
  top: 73.79px;
  position: absolute;
  animation: ldio-37t7hale7vr linear 1s infinite;
  background: var(--primary-accent);
  width: 18.84px;
  height: 40.82px;
  border-radius: 9.42px / 20.41px;
  transform-origin: 9.42px 83.21000000000001px;
}.ldio-37t7hale7vr div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9166666666666666s;
  background: var(--primary-accent);
}.ldio-37t7hale7vr div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.8333333333333334s;
  background: var(--primary-accent);
}.ldio-37t7hale7vr div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.75s;
  background: var(--primary-accent);
}.ldio-37t7hale7vr div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.6666666666666666s;
  background: var(--primary-accent);
}.ldio-37t7hale7vr div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.5833333333333334s;
  background: var(--primary-accent);
}.ldio-37t7hale7vr div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.5s;
  background: var(--primary-accent);
}.ldio-37t7hale7vr div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.4166666666666667s;
  background: var(--primary-accent);
}.ldio-37t7hale7vr div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.3333333333333333s;
  background: var(--primary-accent);
}.ldio-37t7hale7vr div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.25s;
  background: var(--primary-accent);
}.ldio-37t7hale7vr div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.16666666666666666s;
  background: var(--primary-accent);
}.ldio-37t7hale7vr div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.08333333333333333s;
  background: var(--primary-accent);
}.ldio-37t7hale7vr div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: var(--primary-accent);
}
.loadingio-spinner-spinner-c1lc0tehm7v {
  width: 314px;
  height: 314px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-37t7hale7vr {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-37t7hale7vr div { box-sizing: content-box; }
/* generated by https://loading.io/ */

</style>